name: pyddem_environment
channels:
  - conda-forge
  - defaults
dependencies:
  - pybob
  - xarray
  - scikit-gstat
  - netcdf4
  - sphinx-argparse
  - pip
  - pip:
      - pymmaster
      - sphinx-rtd-theme
      - llc
